apiVersion: v1
kind: Template
metadata:
  name: Chipster session replay cronjob
  annotations:
    description: "Program for testing Chipster installation by replaying the jobs in the session files"
    tags: "nodejs,typescript,chipster"
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: ${{NAME}}  
  spec:
    schedule: ${{SCHEDULE}}
    jobTemplate:         
      spec:
        parallelism: 1
        completions: 1
        template:
          spec:
            containers:
            - name: ${{NAME}}
              image: docker-registry.default.svc:5000/${PROJECT}/${IMAGE}
              command: ["node", "lib/replay-session", "-u", "${USERNAME}", "-p", "${PASSWORD}", "-P", "${PARALLEL}", "-r", "${RESULTS}", "${SERVER}", "-F", "${TEST_SET}/"]
              volumeMounts:        
              - mountPath: /home/user/test-data
                name: test-data
            volumes:
            - name: test-data
              persistentVolumeClaim:
                claimName: test-data
            restartPolicy: Never
parameters:
- description: cron schedule
  name: SCHEDULE
- description: cronjob name
  name: NAME
- description: OpenShift project
  name: PROJECT
- description: Chipster username 
  name: USERNAME
- description: Chipster password
  name: PASSWORD
- description: How many jobs are allowed to run in parallel
  name: PARALLEL
- description: Test result directory
  name: RESULTS
- description: URL of the Chipster server
  name: SERVER
- description: Prefix of the server sessions to replay
  name: TEST_SET
- description: image to run
  name: IMAGE
